lista_preguntas = [
{"categoria":"arte","descripcion":"¿Quién pintó La última cena?","respuesta_1":"Leonardo da Vinci","respuesta_2":"Van Gogh","respuesta_3":"Goya","respuesta_4":"Rembrandt","respuesta_correcta":1},
{"categoria":"arte","descripcion":"¿Quién pintó La noche estrellada?","respuesta_1":"Dalí","respuesta_2":"Picasso","respuesta_3":"Monet","respuesta_4":"Van Gogh","respuesta_correcta":4},
{"categoria":"arte","descripcion":"¿El Guernica es obra de...?","respuesta_1":"Picasso","respuesta_2":"Dalí","respuesta_3":"Miró","respuesta_4":"Rivera","respuesta_correcta":1},
{"categoria":"arte","descripcion":"¿Qué instrumento tocaba Mozart?","respuesta_1":"Piano","respuesta_2":"Guitarra","respuesta_3":"Trombón","respuesta_4":"Violín","respuesta_correcta":1},
{"categoria":"arte","descripcion":"¿Qué instrumento tiene 6 cuerdas normalmente?","respuesta_1":"Violín","respuesta_2":"Bajo eléctrico","respuesta_3":"Guitarra","respuesta_4":"Piano","respuesta_correcta":3},
{"categoria":"deporte","descripcion":"¿En qué deporte se usa raqueta?","respuesta_1":"Tenis","respuesta_2":"Rugby","respuesta_3":"Básquet","respuesta_4":"Fútbol","respuesta_correcta":1},
{"categoria":"deporte","descripcion":"¿Cuántos jugadores tiene un equipo de fútbol en cancha?","respuesta_1":"10","respuesta_2":"11","respuesta_3":"12","respuesta_4":"9","respuesta_correcta":2},
{"categoria":"deporte","descripcion":"¿Qué selección ganó el Mundial 2014?","respuesta_1":"España","respuesta_2":"Brasil","respuesta_3":"Alemania","respuesta_4":"Francia","respuesta_correcta":3},
{"categoria":"deporte","descripcion":"¿En qué deporte destacó Michael Jordan?","respuesta_1":"Básquet","respuesta_2":"Tenis","respuesta_3":"Atletismo","respuesta_4":"Boxeo","respuesta_correcta":1},
{"categoria":"deporte","descripcion":"¿En qué deporte destacó Michael Jordan?","respuesta_1":"Básquet","respuesta_2":"Tenis","respuesta_3":"Atletismo","respuesta_4":"Boxeo","respuesta_correcta":1},
{"categoria":"entretenimiento","descripcion":"¿Quién interpretó a Iron Man en el MCU?","respuesta_1":"Chris Evans","respuesta_2":"Robert Downey Jr","respuesta_3":"Mark Ruffalo","respuesta_4":"Tom Holland","respuesta_correcta":2},
{"categoria":"entretenimiento","descripcion":"¿En qué año se estrenó Avatar?","respuesta_1":"2005","respuesta_2":"2009","respuesta_3":"2012","respuesta_4":"2015","respuesta_correcta":2},
{"categoria":"entretenimiento","descripcion":"¿Qué empresa creó la consola PlayStation?","respuesta_1":"Sega","respuesta_2":"Nintendo","respuesta_3":"Sony","respuesta_4":"Microsoft","respuesta_correcta":3},
{"categoria":"entretenimiento","descripcion":"¿Cuál es el videojuego más vendido de la historia?","respuesta_1":"Minecraft","respuesta_2":"Tetris","respuesta_3":"GTA V","respuesta_4":"Fortnite","respuesta_correcta":1},
{"categoria":"entretenimiento","descripcion":"¿Quién escribió El Quijote?","respuesta_1":"Neruda","respuesta_2":"Borges","respuesta_3":"Miguel de Cervantes","respuesta_4":"Shakespeare","respuesta_correcta":3},
{"categoria":"entretenimiento","descripcion":"¿Cuál de estos es un estilo musical?","respuesta_1":"Pastel","respuesta_2":"Jazz","respuesta_3":"Óvalo","respuesta_4":"Clásico","respuesta_correcta":2},
{"categoria":"geografia","descripcion":"¿Capital de Japón?","respuesta_1":"Kioto","respuesta_2":"Tokio","respuesta_3":"Osaka","respuesta_4":"Seúl","respuesta_correcta":2},
{"categoria":"geografia","descripcion":"¿Cuál es el río más largo del mundo según la mayoría?","respuesta_1":"Amazonas","respuesta_2":"Nilo","respuesta_3":"Yangtsé","respuesta_4":"Misisipi","respuesta_correcta":1},
{"categoria":"geografia","descripcion":"¿Capital de Japón?","respuesta_1":"Kioto","respuesta_2":"Tokio","respuesta_3":"Osaka","respuesta_4":"Seúl","respuesta_correcta":2},
{"categoria":"geografia","descripcion":"¿Qué país no tiene salida al mar?","respuesta_1":"España","respuesta_2":"Chile","respuesta_3":"Portugal","respuesta_4":"Bolivia","respuesta_correcta":4},
{"categoria":"geografia","descripcion":"¿Dónde queda el desierto del Sahara?","respuesta_1":"Asia","respuesta_2":"África","respuesta_3":"América","respuesta_4":"Oceanía","respuesta_correcta":2},
{"categoria":"geografia","descripcion":"¿Cuál es el país más grande del mundo?","respuesta_1":"EE.UU","respuesta_2":"China","respuesta_3":"Rusia","respuesta_4":"Canadá","respuesta_correcta":3},
{"categoria":"geografia","descripcion":"¿Cuál es la capital de Canadá?","respuesta_1":"Montreal","respuesta_2":"Toronto","respuesta_3":"Ottawa","respuesta_4":"Vancouver","respuesta_correcta":3},
{"categoria":"geografia","descripcion":"¿Qué continente tiene más países?","respuesta_1":"Europa","respuesta_2":"África","respuesta_3":"Asia","respuesta_4":"América","respuesta_correcta":2},
{"categoria":"geografia","descripcion":"¿Dónde está la Torre Eiffel?","respuesta_1":"Francia","respuesta_2":"Italia","respuesta_3":"Alemania","respuesta_4":"Bélgica","respuesta_correcta":1},
{"categoria":"geografia","descripcion":"¿Cuál es la capital de Australia?","respuesta_1":"Melbourne","respuesta_2":"Sídney","respuesta_3":"Canberra","respuesta_4":"Perth","respuesta_correcta":3},
{"categoria":"historia","descripcion":"¿Dónde se originó el boxeo moderno?","respuesta_1":"EE.UU","respuesta_2":"Grecia","respuesta_3":"Inglaterra","respuesta_4":"Francia","respuesta_correcta":3},
{"categoria":"historia","descripcion":"¿En qué año cayó el Muro de Berlín?","respuesta_1":"1969","respuesta_2":"1975","respuesta_3":"1989","respuesta_4":"1991","respuesta_correcta":3},
{"categoria":"historia","descripcion":"¿Quién fue el primer emperador romano?","respuesta_1":"Julio César","respuesta_2":"Nerón","respuesta_3":"Trajano","respuesta_4":"Augusto","respuesta_correcta":4},
{"categoria":"historia","descripcion":"¿Dónde se originó la democracia?","respuesta_1":"China","respuesta_2":"Grecia","respuesta_3":"Egipto","respuesta_4":"Roma","respuesta_correcta":2},
{"categoria":"historia","descripcion":"¿Quién descubrió América?","respuesta_1":"Cristóbal Colón","respuesta_2":"Magallanes","respuesta_3":"Marco Polo","respuesta_4":"Vasco da Gama","respuesta_correcta":1},
{"categoria":"historia","descripcion":"¿En qué siglo comenzó la Primera Guerra Mundial?","respuesta_1":"Siglo XIX","respuesta_2":"Siglo XX","respuesta_3":"Siglo XVIII","respuesta_4":"Siglo XXI","respuesta_correcta":2},
{"categoria":"historia","descripcion":"¿Quién fue el primer emperador romano?","respuesta_1":"Julio César","respuesta_2":"Nerón","respuesta_3":"Trajano","respuesta_4":"Augusto","respuesta_correcta":4},
{"categoria":"ciencia","descripcion":"¿Qué tipo de animal es un delfín?","respuesta_1":"Mamífero","respuesta_2":"Reptil","respuesta_3":"Pez","respuesta_4":"Anfibio","respuesta_correcta":1},
{"categoria":"ciencia","descripcion":"¿Qué gas respiramos principalmente?","respuesta_1":"Oxígeno","respuesta_2":"Hidrógeno","respuesta_3":"Nitrógeno","respuesta_4":"Helio","respuesta_correcta":3},
{"categoria":"ciencia","descripcion":"¿Cuál es el planeta más grande del sistema solar?","respuesta_1":"Tierra","respuesta_2":"Saturno","respuesta_3":"Júpiter","respuesta_4":"Neptuno","respuesta_correcta":3},
{"categoria":"ciencia","descripcion":"¿Qué órgano bombea la sangre?","respuesta_1":"Corazón","respuesta_2":"Pulmones","respuesta_3":"Hígado","respuesta_4":"Riñones","respuesta_correcta":1},
{"categoria":"ciencia","descripcion":"¿Qué ciencia estudia los seres vivos?","respuesta_1":"Física","respuesta_2":"Astronomía","respuesta_3":"Biología","respuesta_4":"Química","respuesta_correcta":3},
{"categoria":"ciencia","descripcion":"¿Cuál es el metal más liviano?","respuesta_1":"Oro","respuesta_2":"Hierro","respuesta_3":"Plata","respuesta_4":"Litio","respuesta_correcta":4},
{"categoria":"ciencia","descripcion":"¿Cuál es el animal terrestre más rápido?","respuesta_1":"León","respuesta_2":"Caballo","respuesta_3":"Guepardo","respuesta_4":"Lobo","respuesta_correcta":3},
{"categoria":"ciencia","descripcion":"¿Qué figura tiene tres lados?","respuesta_1":"Hexágono","respuesta_2":"Triángulo","respuesta_3":"Cuadrado","respuesta_4":"Círculo","respuesta_correcta":2},
{"categoria":"ciencia","descripcion":"¿Qué animal pone huevos?","respuesta_1":"Perro","respuesta_2":"Pato","respuesta_3":"Gato","respuesta_4":"Caballo","respuesta_correcta":2}
]