# lista_preguntas = [
#     {"descripcion":"¿En qué ciudad nació Lionel Messi?", "respuesta_1":"Rosario","respuesta_2":"Buenos Aires","respuesta_3":"Córdoba","respuesta_correcta":1},
#     {"descripcion": "¿Cuál es la capital de Argentina?", "respuesta_1": "Buenos Aires", "respuesta_2": "Córdoba", "respuesta_3": "Rosario", "respuesta_correcta": 1},
#     {"descripcion": "¿En qué año ganó Argentina su primer mundial de fútbol?", "respuesta_1": "1978", "respuesta_2": "1986", "respuesta_3": "2002", "respuesta_correcta": 1},
#     {"descripcion": "¿Quién es conocido como el 'Padre de la Patria' en Argentina?", "respuesta_1": "Juan Manuel de Rosas", "respuesta_2": "José de San Martín", "respuesta_3": "Manuel Belgrano", "respuesta_correcta": 2},
#     {"descripcion": "¿Cuál es el pico más alto de Argentina?", "respuesta_1": "Cerro Aconcagua", "respuesta_2": "Cerro Tronador", "respuesta_3": "Cerro Fitz Roy", "respuesta_correcta": 1},
#     {"descripcion": "¿Qué río separa a Argentina de Uruguay?", "respuesta_1": "Río Paraná", "respuesta_2": "Río Colorado", "respuesta_3": "Río de la Plata", "respuesta_correcta": 3},
#     {"descripcion": "¿Quién compuso la canción 'Gracias a la Vida'?", "respuesta_1": "Mercedes Sosa", "respuesta_2": "Charly García", "respuesta_3": "Violeta Parra", "respuesta_correcta": 3},
#     {"descripcion": "¿En qué año fue elegido presidente Néstor Kirchner?", "respuesta_1": "2000", "respuesta_2": "2003", "respuesta_3": "2007", "respuesta_correcta": 2},
#     {"descripcion": "¿En qué provincia se encuentra la ciudad de Ushuaia?", "respuesta_1": "Santa Cruz", "respuesta_2": "Chubut", "respuesta_3": "Tierra del Fuego", "respuesta_correcta": 3},
#     {"descripcion": "¿Qué moneda se utiliza en Argentina?", "respuesta_1": "Dólar", "respuesta_2": "Peso", "respuesta_3": "Real", "respuesta_correcta": 2},
#     {"descripcion": "¿Qué famoso cantante argentino popularizó el tango?", "respuesta_1": "Astor Piazzolla", "respuesta_2": "Carlos Gardel", "respuesta_3": "Sandro", "respuesta_correcta": 2},
#     {"descripcion": "¿Cuál es la danza tradicional de Argentina?", "respuesta_1": "Salsa", "respuesta_2": "Cumbia", "respuesta_3": "Tango", "respuesta_correcta": 3},
#     {"descripcion": "¿Cuál es el nombre del famoso glaciar en la Patagonia?", "respuesta_1": "Perito Moreno", "respuesta_2": "Martial", "respuesta_3": "Upsala", "respuesta_correcta": 1},
#     {"descripcion": "¿Quién es el autor de 'Martín Fierro'?", "respuesta_1": "Jorge Luis Borges", "respuesta_2": "José Hernández", "respuesta_3": "Julio Cortázar", "respuesta_correcta": 2},
#     {"descripcion": "¿Cuál es la montaña más alta de América del Sur?", "respuesta_1": "Cerro Bonete", "respuesta_2": "Monte Pissis", "respuesta_3": "Aconcagua", "respuesta_correcta": 3},
#     {"descripcion": "¿Qué bebida es famosa en Argentina?", "respuesta_1": "Tequila", "respuesta_2": "Mate", "respuesta_3": "Pisco", "respuesta_correcta": 2},
#     {"descripcion": "¿Cuál es el nombre del teatro más famoso de Buenos Aires?", "respuesta_1": "Teatro Colón", "respuesta_2": "Teatro Gran Rex", "respuesta_3": "Teatro Nacional", "respuesta_correcta": 1},
#     {"descripcion": "¿Cuál es la Avenida más ancha del mundo ubicada en Buenos Aires?", "respuesta_1": "Avenida de Mayo", "respuesta_2": "Avenida Corrientes", "respuesta_3": "Avenida 9 de Julio", "respuesta_correcta": 3},
#     {"descripcion": "¿Qué prócer argentino creó la bandera?", "respuesta_1": "Domingo Sarmiento", "respuesta_2": "José de San Martín", "respuesta_3": "Manuel Belgrano", "respuesta_correcta": 3},
#     {"descripcion": "¿Qué actriz argentina fue esposa de Juan Domingo Perón?", "respuesta_1": "Tita Merello", "respuesta_2": "Eva Perón", "respuesta_3": "Libertad Lamarque", "respuesta_correcta": 2},
#     {"descripcion": "¿En qué año fue la Guerra de las Malvinas?", "respuesta_1": "1980", "respuesta_2": "1982", "respuesta_3": "1984", "respuesta_correcta": 2},
#     {"descripcion": "¿Cuál es el nombre del equipo de fútbol conocido como 'La Academia'?", "respuesta_1": "Boca Juniors", "respuesta_2": "Racing Club", "respuesta_3": "River Plate", "respuesta_correcta": 2},
#     {"descripcion": "¿En qué provincia se encuentra la ciudad de Mendoza?", "respuesta_1": "Santa Fe", "respuesta_2": "San Juan", "respuesta_3": "Mendoza", "respuesta_correcta": 3},
#     {"descripcion": "¿Cuál es el ave nacional de Argentina?", "respuesta_1": "Cóndor", "respuesta_2": "Ñandú", "respuesta_3": "Hornero", "respuesta_correcta": 3},
#     {"descripcion": "¿Qué escritora argentina ganó el Premio Cervantes en 2018?", "respuesta_1": "Silvina Ocampo", "respuesta_2": "María Elena Walsh", "respuesta_3": "María Teresa Andruetto", "respuesta_correcta": 3},
#     {"descripcion": "¿Qué ciudad argentina es conocida por sus cataratas?", "respuesta_1": "Misiones", "respuesta_2": "Puerto Iguazú", "respuesta_3": "Cataratas de Córdoba", "respuesta_correcta": 2}
# ]

lista_preguntas = [
{"descripcion":"¿Quién interpretó a Iron Man en el MCU?","respuesta_1":"Chris Evans","respuesta_2":"Robert Downey Jr","respuesta_3":"Mark Ruffalo","respuesta_4":"Tom Holland","respuesta_correcta":2},
{"descripcion":"¿En qué año se estrenó Avatar?","respuesta_1":"2005","respuesta_2":"2009","respuesta_3":"2012","respuesta_4":"2015","respuesta_correcta":2},
{"descripcion":"¿Qué empresa creó la consola PlayStation?","respuesta_1":"Sega","respuesta_2":"Nintendo","respuesta_3":"Sony","respuesta_4":"Microsoft","respuesta_correcta":3},
{"descripcion":"¿Cuál es el videojuego más vendido de la historia?","respuesta_1":"Minecraft","respuesta_2":"Tetris","respuesta_3":"GTA V","respuesta_4":"Fortnite","respuesta_correcta":1},
{"descripcion":"¿Quién escribió El Quijote?","respuesta_1":"Neruda","respuesta_2":"Borges","respuesta_3":"Miguel de Cervantes","respuesta_4":"Shakespeare","respuesta_correcta":3},
{"descripcion":"¿Quién pintó La última cena?","respuesta_1":"Leonardo da Vinci","respuesta_2":"Van Gogh","respuesta_3":"Goya","respuesta_4":"Rembrandt","respuesta_correcta":1},
{"descripcion":"¿Cuál de estos es un estilo musical?","respuesta_1":"Pastel","respuesta_2":"Jazz","respuesta_3":"Óvalo","respuesta_4":"Clásico","respuesta_correcta":2},
{"descripcion":"¿Quién pintó La noche estrellada?","respuesta_1":"Dalí","respuesta_2":"Picasso","respuesta_3":"Monet","respuesta_4":"Van Gogh","respuesta_correcta":4},
{"descripcion":"¿Qué instrumento tocaba Mozart?","respuesta_1":"Piano","respuesta_2":"Guitarra","respuesta_3":"Trombón","respuesta_4":"Violín","respuesta_correcta":1},
{"descripcion":"¿El Guernica es obra de...?","respuesta_1":"Picasso","respuesta_2":"Dalí","respuesta_3":"Miró","respuesta_4":"Rivera","respuesta_correcta":1},
{"descripcion":"¿En qué deporte se usa raqueta?","respuesta_1":"Tenis","respuesta_2":"Rugby","respuesta_3":"Básquet","respuesta_4":"Fútbol","respuesta_correcta":1},
{"descripcion":"¿Cuántos jugadores tiene un equipo de fútbol en cancha?","respuesta_1":"10","respuesta_2":"11","respuesta_3":"12","respuesta_4":"9","respuesta_correcta":2},
{"descripcion":"¿Dónde se originó el boxeo moderno?","respuesta_1":"EE.UU","respuesta_2":"Grecia","respuesta_3":"Inglaterra","respuesta_4":"Francia","respuesta_correcta":3},
{"descripcion":"¿Qué selección ganó el Mundial 2014?","respuesta_1":"España","respuesta_2":"Brasil","respuesta_3":"Alemania","respuesta_4":"Francia","respuesta_correcta":3},
{"descripcion":"¿En qué deporte destacó Michael Jordan?","respuesta_1":"Básquet","respuesta_2":"Tenis","respuesta_3":"Atletismo","respuesta_4":"Boxeo","respuesta_correcta":1},
{"descripcion":"¿Cuál es el río más largo del mundo según la mayoría?","respuesta_1":"Amazonas","respuesta_2":"Nilo","respuesta_3":"Yangtsé","respuesta_4":"Misisipi","respuesta_correcta":1},
{"descripcion":"¿Capital de Japón?","respuesta_1":"Kioto","respuesta_2":"Tokio","respuesta_3":"Osaka","respuesta_4":"Seúl","respuesta_correcta":2},
{"descripcion":"¿Qué país no tiene salida al mar?","respuesta_1":"España","respuesta_2":"Chile","respuesta_3":"Portugal","respuesta_4":"Bolivia","respuesta_correcta":4},
{"descripcion":"¿Dónde queda el desierto del Sahara?","respuesta_1":"Asia","respuesta_2":"África","respuesta_3":"América","respuesta_4":"Oceanía","respuesta_correcta":2},
{"descripcion":"¿Cuál es el país más grande del mundo?","respuesta_1":"EE.UU","respuesta_2":"China","respuesta_3":"Rusia","respuesta_4":"Canadá","respuesta_correcta":3},
{"descripcion":"¿En qué año cayó el Muro de Berlín?","respuesta_1":"1969","respuesta_2":"1975","respuesta_3":"1989","respuesta_4":"1991","respuesta_correcta":3},
{"descripcion":"¿Quién fue el primer emperador romano?","respuesta_1":"Julio César","respuesta_2":"Nerón","respuesta_3":"Trajano","respuesta_4":"Augusto","respuesta_correcta":4},
{"descripcion":"¿Dónde se originó la democracia?","respuesta_1":"China","respuesta_2":"Grecia","respuesta_3":"Egipto","respuesta_4":"Roma","respuesta_correcta":2},
{"descripcion":"¿Quién descubrió América?","respuesta_1":"Cristóbal Colón","respuesta_2":"Magallanes","respuesta_3":"Marco Polo","respuesta_4":"Vasco da Gama","respuesta_correcta":1},
{"descripcion":"¿En qué siglo comenzó la Primera Guerra Mundial?","respuesta_1":"Siglo XIX","respuesta_2":"Siglo XX","respuesta_3":"Siglo XVIII","respuesta_4":"Siglo XXI","respuesta_correcta":2},
{"descripcion":"¿Qué tipo de animal es un delfín?","respuesta_1":"Mamífero","respuesta_2":"Reptil","respuesta_3":"Pez","respuesta_4":"Anfibio","respuesta_correcta":1},
{"descripcion":"¿Qué gas respiramos principalmente?","respuesta_1":"Oxígeno","respuesta_2":"Hidrógeno","respuesta_3":"Nitrógeno","respuesta_4":"Helio","respuesta_correcta":3},
{"descripcion":"¿Cuál es el planeta más grande del sistema solar?","respuesta_1":"Tierra","respuesta_2":"Saturno","respuesta_3":"Júpiter","respuesta_4":"Neptuno","respuesta_correcta":3},
{"descripcion":"¿Qué órgano bombea la sangre?","respuesta_1":"Corazón","respuesta_2":"Pulmones","respuesta_3":"Hígado","respuesta_4":"Riñones","respuesta_correcta":1},
{"descripcion":"¿Qué ciencia estudia los seres vivos?","respuesta_1":"Física","respuesta_2":"Astronomía","respuesta_3":"Biología","respuesta_4":"Química","respuesta_correcta":3},
{"descripcion":"¿Cuál es el metal más liviano?","respuesta_1":"Oro","respuesta_2":"Hierro","respuesta_3":"Plata","respuesta_4":"Litio","respuesta_correcta":4},
{"descripcion":"¿Cuál es la capital de Canadá?","respuesta_1":"Montreal","respuesta_2":"Toronto","respuesta_3":"Ottawa","respuesta_4":"Vancouver","respuesta_correcta":3},
{"descripcion":"¿Cuál es el animal terrestre más rápido?","respuesta_1":"León","respuesta_2":"Caballo","respuesta_3":"Guepardo","respuesta_4":"Lobo","respuesta_correcta":3},
{"descripcion":"¿Quién escribió Romeo y Julieta?","respuesta_1":"Poe","respuesta_2":"Tolstói","respuesta_3":"Dickens","respuesta_4":"Shakespeare","respuesta_correcta":4},
{"descripcion":"¿Qué continente tiene más países?","respuesta_1":"Europa","respuesta_2":"África","respuesta_3":"Asia","respuesta_4":"América","respuesta_correcta":2},
{"descripcion":"¿Qué país inventó la pizza moderna?","respuesta_1":"Italia","respuesta_2":"Francia","respuesta_3":"Grecia","respuesta_4":"España","respuesta_correcta":1},
{"descripcion":"¿Cuál es la moneda del Reino Unido?","respuesta_1":"Euro","respuesta_2":"Dólar","respuesta_3":"Libra esterlina","respuesta_4":"Franco","respuesta_correcta":3},
{"descripcion":"¿Qué océano es el más grande?","respuesta_1":"Índico","respuesta_2":"Pacífico","respuesta_3":"Atlántico","respuesta_4":"Ártico","respuesta_correcta":2},
{"descripcion":"¿Qué animal pone huevos?","respuesta_1":"Perro","respuesta_2":"Pato","respuesta_3":"Gato","respuesta_4":"Caballo","respuesta_correcta":2},
{"descripcion":"¿Dónde está la Torre Eiffel?","respuesta_1":"Francia","respuesta_2":"Italia","respuesta_3":"Alemania","respuesta_4":"Bélgica","respuesta_correcta":1},
{"descripcion":"¿Qué instrumento tiene 6 cuerdas normalmente?","respuesta_1":"Violín","respuesta_2":"Bajo eléctrico","respuesta_3":"Guitarra","respuesta_4":"Piano","respuesta_correcta":3},
{"descripcion":"¿Qué figura tiene tres lados?","respuesta_1":"Hexágono","respuesta_2":"Triángulo","respuesta_3":"Cuadrado","respuesta_4":"Círculo","respuesta_correcta":2},
{"descripcion":"¿Qué planeta es el planeta rojo?","respuesta_1":"Júpiter","respuesta_2":"Venus","respuesta_3":"Marte","respuesta_4":"Saturno","respuesta_correcta":3},
{"descripcion":"¿Cuál es el idioma más hablado del mundo?","respuesta_1":"Inglés","respuesta_2":"Hindi","respuesta_3":"Español","respuesta_4":"Chino mandarín","respuesta_correcta":4},
{"descripcion":"¿Cuál es la capital de Australia?","respuesta_1":"Melbourne","respuesta_2":"Sídney","respuesta_3":"Canberra","respuesta_4":"Perth","respuesta_correcta":3}
]